export default {
    cardWithTask: {
        passTest: 'Take Test',
        passTestToUnlock: 'Pass the test to unlock tasks',
        skipped: 'SKIPPED',
        success: 'SUCCESS',
        complete: 'Complete',
        start: 'Start',
        skip: 'Skip',
        updating: 'Updating...',
        starting: 'Starting...',
        skipping: 'Skipping...'
    },
    userPage: {
        alphaVersion: 'alpha version',
        years: 'years',
        yourActivity: 'Your Activity',
        less: 'Less',
        more: 'More',
        totalScore: 'Total Score',
        completed: 'Completed',
        missed: 'Missed',
        startYourJourney: 'Start Your Journey',
        passShortTest: 'Take a short test to unlock all platform features',
        benefits: {
            unlockTasks: 'Unlock tasks',
            trackProgress: 'Track progress',
            earnRewards: 'Earn rewards'
        }
    },
    lsas: {
        title: 'Liebowitz Social Anxiety Scale',
        description: 'Please rate your fear/anxiety and avoidance for each situation described below.',
        fearLabel: 'Fear/Anxiety Level',
        avoidanceLabel: 'Avoidance Level',
        fearOptions: ['None', 'Mild', 'Moderate', 'Severe'],
        avoidanceOptions: ['Never', 'Occasionally', 'Often', 'Usually'],
        selectOption: 'Select...',
        progress: 'Progress',
        next: 'Next',
        back: 'Back',
        complete: 'Complete Test',
        processing: 'Processing...',
        cancel: 'Cancel',
        resultsTitle: 'Assessment Results',
        anxietyScore: 'Anxiety Score',
        resultsDescription: 'Based on your assessment, we have created personalized tasks to help you reduce anxiety and improve wellbeing.',
        viewTasks: 'View Your Tasks',
        loading: 'Loading...',
        questions: [
            'Telephoning in public',
            'Participating in small groups',
            'Eating in public places',
            'Writing while someone watches',
            'Being the center of attention',
            'Speaking up at a meeting',
            'Meeting strangers',
            'Talking to people in authority',
            'Talking with unfamiliar people at a party',
            'Going to a party',
            'Participating in meetings',
            'Talking to a stranger',
            'Looking someone in the eyes',
            'Speaking to an attractive person',
            'Drinking with others in public places',
            'Returning goods to a store',
            'Talking to clerks or waiters',
            'Going to a party where you know few people',
            'Asserting yourself in a disagreement',
            'Starting a conversation with a group',
            'Entering a room when others are already seated',
            'Being in a waiting room with other people',
            'Using a public restroom',
            'Walking down the street or riding in a bus'
        ]
    }
}; 